### ISSUE TITLE
CMS Roadmap

### ISSUE THREAD

**Issue by AleksandarDev** [gredice/gredice#61]
- [ ] Entity progress (using required attribute definitions)
- [ ] Reorder attributes
- [ ] Reorder categories
- [ ] Reorder attribute types (in left menu)
- [ ] Entity type icon
- [ ] Attribute descriptions/helper text
- [ ] Publishing entities
- [ ] References
- [ ] Root/Shadow entity types (for references)
- [ ] Hierarchy (TODO idea)
- [ ] Unwrap complex attribute definition data types to refs
- [ ] Variants (inherit and override)
- [ ] Display attributes (mark attributes as display to display in CMS)
- [ ] Versioning entities
- [ ] History of entity attributes values
